In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/summer-analytics-mid-hackathon/hacktest.csv
/kaggle/input/summer-analytics-mid-hackathon/hacktrain.csv

In [2]:
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
train_df = pd.read_csv("/kaggle/input/summer-analytics-mid-hackathon/hacktrain.csv")
test_df = pd.read_csv("/kaggle/input/summer-analytics-mid-hackathon/hacktest.csv")

train_df

,Unnamed: 0,ID,class,20150720_N,20150602_N,20150517_N,20150501_N,20150415_N,20150330_N,20150314_N,...,20140610_N,20140525_N,20140509_N,20140423_N,20140407_N,20140322_N,20140218_N,20140202_N,20140117_N,20140101_N
0,0,1,water,637.5950,658.668,-1882.030,-1924.36,997.904,-1739.990,630.087,...,NaN,-1043.160,-1942.490,267.138,NaN,NaN,211.328,-2203.020,-1180.19,433.906
1,1,2,water,634.2400,593.705,-1625.790,-1672.32,914.198,-692.386,707.626,...,NaN,-933.934,-625.385,120.059,364.858,476.972,220.878,-2250.000,-1360.56,524.075
2,3,4,water,58.0174,-1599.160,NaN,-1052.63,NaN,-1564.630,NaN,...,-1025.880,368.622,NaN,-1227.800,304.621,NaN,369.214,-2202.120,NaN,-1343.550
3,4,5,water,72.5180,NaN,380.436,-1256.93,515.805,-1413.180,-802.942,...,-1813.950,155.624,NaN,-924.073,432.150,282.833,298.320,-2197.360,NaN,-826.727
4,7,8,water,1136.4400,NaN,NaN,1647.83,1935.800,NaN,2158.980,...,1535.000,1959.430,-279.317,-384.915,-113.406,1020.720,1660.650,-116.801,-568.05,-1357.140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,10537,10538,impervious,1207.7000,984.620,NaN,1166.25,937.478,1072.700,823.896,...,1117.740,1176.600,1044.110,NaN,369.082,465.843,362.882,979.795,NaN,433.659
7996,10538,10539,impervious,2170.3500,1419.720,1361.000,1478.71,983.911,1262.110,1422.860,...,984.634,2128.970,1379.660,NaN,762.633,485.204,446.724,771.747,1589.06,506.936
7997,10541,10542,impervious,1895.6800,1454.740,NaN,1033.56,1930.380,1057.150,1471.600,...,888.408,2093.020,1232.110,1190.830,1441.460,1170.880,1095.000,1818.650,2501.72,1247.770
7998,10542,10543,impervious,3465.7400,1283.320,413.412,4391.05,1146.820,4473.050,1614.750,...,5833.760,4047.320,4515.800,433.177,277.296,744.143,NaN,3759.710,NaN,388.346
7999,10544,10545,impervious,6941.1900,1667.870,5084.780,NaN,1588.950,5978.190,NaN,...,7352.570,3289.860,3729.150,1994.980,NaN,5299.900,NaN,5983.130,1249.71,2424.230

In [3]:
train_df.nunique()

Unnamed: 0    8000
ID            8000
class            6
20150720_N    7357
20150602_N    6756
20150517_N    7160
20150501_N    7011
20150415_N    7502
20150330_N    6843
20150314_N    7255
20150226_N    6609
20150210_N    7329
20150125_N    6913
20150109_N    7106
20141117_N    6705
20141101_N    7587
20141016_N    6533
20140930_N    7179
20140813_N    7390
20140626_N    6366
20140610_N    7474
20140525_N    7247
20140509_N    7087
20140423_N    6217
20140407_N    7330
20140322_N    6852
20140218_N    6537
20140202_N    7350
20140117_N    6773
20140101_N    7567
dtype: int64

In [4]:
train_df.shape

(8000, 30)

In [5]:
# let's use limited columns which makes more sense for serving our purpose

cols_to_use = ['Unnamed: 0', 'ID', 'class', '20150720_N', '20150602_N', '20150517_N',
       '20150501_N', '20150415_N', '20150330_N', '20150314_N', '20150226_N',
       '20150210_N', '20150125_N', '20150109_N', '20141117_N', '20141101_N',
       '20141016_N', '20140930_N', '20140813_N', '20140626_N', '20140610_N',
       '20140525_N', '20140509_N', '20140423_N', '20140407_N', '20140322_N',
       '20140218_N', '20140202_N', '20140117_N', '20140101_N']

dataset = train_df[cols_to_use]
dataset

,Unnamed: 0,ID,class,20150720_N,20150602_N,20150517_N,20150501_N,20150415_N,20150330_N,20150314_N,...,20140610_N,20140525_N,20140509_N,20140423_N,20140407_N,20140322_N,20140218_N,20140202_N,20140117_N,20140101_N
0,0,1,water,637.5950,658.668,-1882.030,-1924.36,997.904,-1739.990,630.087,...,NaN,-1043.160,-1942.490,267.138,NaN,NaN,211.328,-2203.020,-1180.19,433.906
1,1,2,water,634.2400,593.705,-1625.790,-1672.32,914.198,-692.386,707.626,...,NaN,-933.934,-625.385,120.059,364.858,476.972,220.878,-2250.000,-1360.56,524.075
2,3,4,water,58.0174,-1599.160,NaN,-1052.63,NaN,-1564.630,NaN,...,-1025.880,368.622,NaN,-1227.800,304.621,NaN,369.214,-2202.120,NaN,-1343.550
3,4,5,water,72.5180,NaN,380.436,-1256.93,515.805,-1413.180,-802.942,...,-1813.950,155.624,NaN,-924.073,432.150,282.833,298.320,-2197.360,NaN,-826.727
4,7,8,water,1136.4400,NaN,NaN,1647.83,1935.800,NaN,2158.980,...,1535.000,1959.430,-279.317,-384.915,-113.406,1020.720,1660.650,-116.801,-568.05,-1357.140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,10537,10538,impervious,1207.7000,984.620,NaN,1166.25,937.478,1072.700,823.896,...,1117.740,1176.600,1044.110,NaN,369.082,465.843,362.882,979.795,NaN,433.659
7996,10538,10539,impervious,2170.3500,1419.720,1361.000,1478.71,983.911,1262.110,1422.860,...,984.634,2128.970,1379.660,NaN,762.633,485.204,446.724,771.747,1589.06,506.936
7997,10541,10542,impervious,1895.6800,1454.740,NaN,1033.56,1930.380,1057.150,1471.600,...,888.408,2093.020,1232.110,1190.830,1441.460,1170.880,1095.000,1818.650,2501.72,1247.770
7998,10542,10543,impervious,3465.7400,1283.320,413.412,4391.05,1146.820,4473.050,1614.750,...,5833.760,4047.320,4515.800,433.177,277.296,744.143,NaN,3759.710,NaN,388.346
7999,10544,10545,impervious,6941.1900,1667.870,5084.780,NaN,1588.950,5978.190,NaN,...,7352.570,3289.860,3729.150,1994.980,NaN,5299.900,NaN,5983.130,1249.71,2424.230

In [6]:
dataset.isna().sum()

Unnamed: 0       0
ID               0
class            0
20150720_N     560
20150602_N    1200
20150517_N     800
20150501_N     960
20150415_N     480
20150330_N    1120
20150314_N     720
20150226_N    1360
20150210_N     640
20150125_N    1040
20150109_N     880
20141117_N    1280
20141101_N     400
20141016_N    1440
20140930_N     800
20140813_N     560
20140626_N    1600
20140610_N     480
20140525_N     720
20140509_N     880
20140423_N    1760
20140407_N     640
20140322_N    1120
20140218_N    1440
20140202_N     560
20140117_N    1200
20140101_N     400
dtype: int64

In [7]:

ndvi_cols = [col for col in dataset.columns if '_N' in col]
dataset[ndvi_cols] = dataset[ndvi_cols].interpolate(axis=1).bfill(axis=1).ffill(axis=1)
dataset['ndvi_mean'] = dataset[ndvi_cols].mean(axis=1)
dataset['ndvi_std'] = dataset[ndvi_cols].std(axis=1)
dataset['ndvi_range'] = dataset[ndvi_cols].max(axis=1) - dataset[ndvi_cols].min(axis=1)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
# y = le.fit_transform(df['class'])
dataset['class'] = le.fit_transform(dataset['class'])

In [8]:
dataset.isna().sum()

Unnamed: 0    0
ID            0
class         0
20150720_N    0
20150602_N    0
20150517_N    0
20150501_N    0
20150415_N    0
20150330_N    0
20150314_N    0
20150226_N    0
20150210_N    0
20150125_N    0
20150109_N    0
20141117_N    0
20141101_N    0
20141016_N    0
20140930_N    0
20140813_N    0
20140626_N    0
20140610_N    0
20140525_N    0
20140509_N    0
20140423_N    0
20140407_N    0
20140322_N    0
20140218_N    0
20140202_N    0
20140117_N    0
20140101_N    0
ndvi_mean     0
ndvi_std      0
ndvi_range    0
dtype: int64

In [9]:
X = dataset.iloc[:, 0:1]
y = dataset.iloc[:, 1]
X = dataset.drop(['ID', 'class'], axis=1)
y = dataset['class']
from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X, y, stratify=y,test_size=0.2, random_state=42)

In [10]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000, multi_class='multinomial', solver='lbfgs')
model.fit(train_X, train_y)

LogisticRegression(max_iter=1000, multi_class='multinomial')

In [11]:
train_X.shape

(6400, 31)

In [12]:
train_y.shape

(6400,)

In [13]:
from sklearn.metrics import accuracy_score, classification_report
y_pred = model.predict(test_X) #calculating prediction score 
#by first predicting and then calculating also called accuracy
print("Accuracy:", accuracy_score(test_y, y_pred))
print(classification_report(test_y, y_pred))

Accuracy: 0.951875
              precision    recall  f1-score   support

           0       0.83      0.87      0.85       168
           1       0.99      0.99      0.99      1232
           2       0.86      0.62      0.72        39
           3       0.81      0.85      0.83       134
           4       0.40      0.33      0.36         6
           5       0.79      0.71      0.75        21

    accuracy                           0.95      1600
   macro avg       0.78      0.73      0.75      1600
weighted avg       0.95      0.95      0.95      1600

In [14]:
print("Training features:", train_df.columns)
print("Test features:", test_df.columns)

Training features: Index(['Unnamed: 0', 'ID', 'class', '20150720_N', '20150602_N', '20150517_N',
       '20150501_N', '20150415_N', '20150330_N', '20150314_N', '20150226_N',
       '20150210_N', '20150125_N', '20150109_N', '20141117_N', '20141101_N',
       '20141016_N', '20140930_N', '20140813_N', '20140626_N', '20140610_N',
       '20140525_N', '20140509_N', '20140423_N', '20140407_N', '20140322_N',
       '20140218_N', '20140202_N', '20140117_N', '20140101_N'],
      dtype='object')
Test features: Index(['Unnamed: 0', 'ID', '20150720_N', '20150602_N', '20150517_N',
       '20150501_N', '20150415_N', '20150330_N', '20150314_N', '20150226_N',
       '20150210_N', '20150125_N', '20150109_N', '20141117_N', '20141101_N',
       '20141016_N', '20140930_N', '20140813_N', '20140626_N', '20140610_N',
       '20140525_N', '20140509_N', '20140423_N', '20140407_N', '20140322_N',
       '20140218_N', '20140202_N', '20140117_N', '20140101_N'],
      dtype='object')

In [15]:
# Make Final Predictions
test_df = pd.read_csv('/kaggle/input/summer-analytics-mid-hackathon/hacktest.csv')



test_df[ndvi_cols] = test_df[ndvi_cols].interpolate(axis=1).bfill(axis=1).ffill(axis=1)
test_df['ndvi_mean'] = test_df[ndvi_cols].mean(axis=1)
test_df['ndvi_std'] = test_df[ndvi_cols].std(axis=1)
test_df['ndvi_range'] = test_df[ndvi_cols].max(axis=1) - test_df[ndvi_cols].min(axis=1)



preds = model.predict(test_df.drop(['ID'], axis=1))
test_df['class'] = le.inverse_transform(preds)
test_df[['ID', 'class']].to_csv('submission.csv', index=False)